{"name": "test_func", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = func(3)", "trace": "def test_func():    #自动找test_开头的测试函数执行\n>       assert func(3) == 5\nE       assert 4 == 5\nE        +  where 4 = func(3)\n\ntest_sample.py:15: AssertionError"}, "start": 1602222523607, "stop": 1602222523608, "uuid": "166f81fe-eb24-49c9-9d2c-5d7b60cc9b09", "historyId": "c53e8cd8e67edf320152ee86febd0eb4", "testCaseId": "da75bd7faa724c9da60f90de8c588c31", "fullName": "test_sample#test_func", "labels": [{"name": "suite", "value": "test_sample"}, {"name": "host", "value": "DESKTOP-MSC5KCU"}, {"name": "thread", "value": "4988-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_sample"}]}